before_commands:
    - composer self-update --2  # Upgrade to Composer 2
    - composer install --no-interaction --no-scripts  # Install dependencies
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_coverage:
        enabled: true
    external_code_coverage:
        timeout: 600
build:
    nodes:
        analysis:
            environment:
                php:
                    version: 8.3  # Specify PHP version
            tests:
                override: [php-scrutinizer-run]
