before_commands:
    # Install PHP 8.3 manually
    - sudo add-apt-repository ppa:ondrej/php -y
    - sudo apt-get update -y
    - sudo apt-get install php8.3-cli -y
    - php -v # Check PHP version to ensure 8.3 is installed
    - composer self-update --2  # Upgrade to Composer 2
    - composer install --no-interaction --no-scripts  # Install dependencies
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_coverage:
        enabled: true
    external_code_coverage:
        timeout: 600
build:
    image: default-bionic
    nodes:
        analysis:
            tests:
                override: [php-scrutinizer-run]