before_commands:
    - composer self-update --2  # Upgrade to Composer 2
    - composer install --no-interaction --no-scripts  # Install dependencies
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_coverage:
        enabled: true
    external_code_coverage:
        timeout: 600
build:
    image: default-bionic
    nodes:
        analysis:
            dependencies:
                before:
                    - composer self-update --2  # Upgrade to Composer 2
                    - composer install --no-interaction --no-scripts  # Install dependencies
                    # Install PHP 8.3 manually
                    - sudo apt-get update
                    - sudo apt-get install -y software-properties-common
                    - sudo add-apt-repository ppa:ondrej/php -y
                    - sudo apt-get update -y
                    - sudo apt-get install php8.3 php8.3-cli -y
                    - php -v # Check PHP version to ensure 8.3 is installed
            tests:
                override: [php-scrutinizer-run]