name: phpunit-tests

on:
  push:
  pull_request:
  schedule:
   - cron: "0 9 * * 1"

jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.3']
        coverage-driver: [pcov]
    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gmp
          coverage: pcov
          tools: composer:v2, infection

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Update composer
        run: composer self-update

      - name: Composer install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          composer install -n
          composer require scrutinizer/ocular --no-update --no-interaction

      - name: PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-text --coverage-html=coverage
        env:
          XDEBUG_MODE: coverage

      - name: Archive Code Coverage Results
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Code Coverage To Scrutinizer
        run: vendor/bin/ocular code-coverage:upload --format=php-clover coverage.xml